domain_path: /home/user/work/FY25/03_project/VoiceNote/sw/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/user/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
